### ISSUE TITLE
fix: CMS bug, hitting enter in a list item doesn't break the current line

### ISSUE THREAD

**Issue by hollandjg** [thepolicylab-projectportals/project-portal-theme#275]
Hitting enter in the middle of a numbered line generates a new line, but doesn’t send the text to the right of the cursor to the next line.

<img width="673" alt="image (1)" src="https://user-images.githubusercontent.com/2803227/201679616-4eebe39b-f033-4ba5-897f-0f8511af67df.png">
<img width="671" alt="image (2)" src="https://user-images.githubusercontent.com/2803227/201679636-baf60385-192a-4eff-97bd-a1d1a737f0b8.png">

**Comment by jashlu** [comment]
look into manually updating Decap dependency, to most updated version which contains a fix for this bug
