### ISSUE TITLE
feature: add email sign-up box linked to mail chimp

### ISSUE THREAD

**Issue by hollandjg** [thepolicylab-projectportals/project-portal-theme#397]
... as a separate plugin for the theme

**Comment by hollandjg** [comment]
- [ ] implement as external link
- [ ] PR for external links in Navbar
- [ ] PR with mailing list sign up box on Project Detail Page
- [ ] PR Option to add the link to the bottom banner

**Comment by hetd54** [comment]
Decided to not have option for bottom banner
