### ISSUE TITLE
fix weird formatting of titles on project detail pages

### ISSUE THREAD

**Issue by hollandjg** [thepolicylab-projectportals/project-portal-theme#716]
Titles ("Question") on Project Detail pages are looking strange – they're breaking in the wrong place. Doesn't look to be affecting productive sites, but perhaps it's something we've done in the formatting of the previews.

![Screenshot 2023-11-28 at 12 12 17](https://github.com/thepolicylab-projectportals/project-portal-theme/assets/2803227/a69844a4-e6db-47fc-8c02-fef41c610af1)

**Comment by jashlu** [comment]
I believe this is just the nature of the styling we've done, this also happens if u build the site locally. It just so happens that the questions (Titles) are way longer on the production sites that they appear to "break better". I'll make some adjustments to the styling
